services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "https://archive.org/download/19044.1586.220303-0132.21-h-2-release-svc-prod-1-clientmulti-x-64-fre-en-us/19044.1586.220303-0132.21H2_RELEASE_SVC_PROD1_CLIENTMULTI_X64FRE_EN-US.ISO"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
